### ISSUE TITLE
Error with evaluation processes.

### ISSUE THREAD

**Issue by smatsumori** [takuseno/nec#13]
```
evaluation starts
Xlib:  extension "GLX" missing on display ":1049".
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    main()
  File "train.py", line 181, in main
    trainer.start()
  File "/home/smatsumori/.pyenv/versions/tensorflow3/lib/python3.6/site-packages/lightsaber/rl/trainer.py", line 127, in start
    self.evaluate()
  File "/home/smatsumori/.pyenv/versions/tensorflow3/lib/python3.6/site-packages/lightsaber/rl/trainer.py", line 176, in evaluate
    agent, self.global_step, self.episode)
  File "/home/smatsumori/.pyenv/versions/tensorflow3/lib/python3.6/site-packages/lightsaber/rl/evaluator.py", line 45, in start
    self.env.render()
  File "/home/smatsumori/.pyenv/versions/tensorflow3/lib/python3.6/site-packages/lightsaber/rl/env_wrapper.py", line 36, in render
    return self.env.render(mode=mode)
  File "/home/smatsumori/.pyenv/versions/tensorflow3/lib/python3.6/site-packages/gym/core.py", line 284, in render
    return self.env.render(mode)
  File "/home/smatsumori/.pyenv/versions/tensorflow3/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 107, in render
    from gym.envs.classic_control import rendering
  File "/home/smatsumori/.pyenv/versions/tensorflow3/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 23, in <module>
    from pyglet.gl import *
  File "/home/smatsumori/.pyenv/versions/tensorflow3/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 239, in <module>
    import pyglet.window
  File "/home/smatsumori/.pyenv/versions/tensorflow3/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1896, in <module>
    gl._create_shadow_window()
  File "/home/smatsumori/.pyenv/versions/tensorflow3/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 208, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home/smatsumori/.pyenv/versions/tensorflow3/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 166, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/smatsumori/.pyenv/versions/tensorflow3/lib/python3.6/site-packages/pyglet/window/__init__.py", line 512, in __init__
    config = screen.get_best_config(template_config)
  File "/home/smatsumori/.pyenv/versions/tensorflow3/lib/python3.6/site-packages/pyglet/canvas/base.py", line 159, in get_best_config
    configs = self.get_matching_configs(template)
  File "/home/smatsumori/.pyenv/versions/tensorflow3/lib/python3.6/site-packages/pyglet/canvas/xlib.py", line 182, in get_matching_configs
    configs = template.match(canvas)
  File "/home/smatsumori/.pyenv/versions/tensorflow3/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 31, in match
    have_13 = info.have_version(1, 3)
  File "/home/smatsumori/.pyenv/versions/tensorflow3/lib/python3.6/site-packages/pyglet/gl/glx_info.py", line 84, in have_version
    raise GLXInfoException('pyglet requires an X server with GLX')
pyglet.gl.glx_info.GLXInfoException: pyglet requires an X server with GLX
```

**Comment by smatsumori** [comment]
## This might be a solution?
https://github.com/openai/gym/issues/366

**Comment by takuseno** [comment]
setting virtualdisplay to 2049 might solve the problem?
