### ISSUE TITLE
Invalid Argument Error.

### ISSUE THREAD

**Issue by smatsumori** [takuseno/nec#7]
```InvalidArgumentError (see above for traceback): Incompatible shapes: [32] vs. [3]
	 [[Node: deepq/gradients/deepq/sub_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](deepq/gradients/deepq/sub_grad/Shape, deepq/gradients/deepq/sub_grad/Shape_1)]]
```

**Comment by smatsumori** [comment]
```
Episode: 1, Step: 1036: Reward: -21.0
Episode: 2, Step: 2061: Reward: -20.0
Episode: 3, Step: 3025: Reward: -21.0
Episode: 4, Step: 3817: Reward: -21.0
Episode: 5, Step: 4880: Reward: -20.0
Episode: 6, Step: 5995: Reward: -19.0
Episode: 7, Step: 6914: Reward: -20.0
Episode: 8, Step: 7766: Reward: -21.0
Episode: 9, Step: 8756: Reward: -20.0
Episode: 10, Step: 9580: Reward: -21.0
2018-02-20 18:37:57.133421: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32] vs. [3]
	 [[Node: deepq/gradients/deepq/sub_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](deepq/gradients/deepq/sub_grad/Shape, deepq/gradients/deepq/sub_grad/Shape_1)]]
Traceback (most recent call last):
  File "/home/smatsumori/.virtualenvs/tensorflow3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/smatsumori/.virtualenvs/tensorflow3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/smatsumori/.virtualenvs/tensorflow3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [32] vs. [3]
	 [[Node: deepq/gradients/deepq/sub_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](deepq/gradients/deepq/sub_grad/Shape, deepq/gradients/deepq/sub_grad/Shape_1)]]
	 [[Node: deepq/Sum_1/_633 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1833_deepq/Sum_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

```
